version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports: 
      - "80:80"
    networks:
      - internal
    volumes:
      - ../src/:/var/www/html/
      -  /logs/nginx:/var/log/nginx/
  php:
    build:
      context: .
      dockerfile: php/DockerfilePHP
    networks:
      - internal
    volumes:
      - ../src/:/var/www/html
  composer:
    image: composer/composer:latest
    command: composer install
    networks:
      - internal
    volumes:
      - ../src/:/var/www/html
    depends_on:
      - php
networks:
  internal:
    driver: bridge